openapi: 3.0.0
x-stoplight:
  id: akb7f5psdzhz7
info:
  title: AI Failure Detection APIs
  version: '1.0'
  description: 'API definitions. For a detailed explanation, [see the API overview.](https://octoeverywhere.stoplight.io/docs/octoeverywhere-api-docs/3xadck728cc0t-ai-failure-detection-ap-is)'
servers: []
paths:
  /api/gadget/v1/createcontext:
    parameters: []
    servers:
      - url: 'https://gadget-pv1-oeapi.octoeverywhere.com'
        description: ''
    post:
      summary: Create Context
      tags: []
      responses: {}
      operationId: create-context
      x-stoplight:
        id: kgomtjwkt3dj9
      description: "The Create Context API allows for the creation of a new context for AI failure detection.\r\n\r\nFor a detailed explanation, [see the API overview.](https://octoeverywhere.stoplight.io/docs/octoeverywhere-api-docs/3xadck728cc0t-ai-failure-detection-ap-is)"
      parameters:
        - schema:
            type: string
          in: header
          name: X-API-Key
          description: You OctoEverywhere developer API key.
    get:
      description: ''
  '/api/gadget/v1/process/{ID}':
    get:
      summary: Process API
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  NextProcessIntervalSec:
                    type: integer
                    x-stoplight:
                      id: pjl40jjr6xp76
                    default: 40
                    description: The minimum interval between the response and the next Process API call is in seconds.
                  Score:
                    type: integer
                    x-stoplight:
                      id: yqo01rkjkuc49
                    minimum: 0
                    maximum: 100
                    description: 'The current temporal combination model''s probability of failure. 0 is a perfect print, 100 is very likely a failure.'
                  WarningSuggested:
                    type: boolean
                    x-stoplight:
                      id: ibt3s7is2i87o
                  PauseSuggested:
                    type: boolean
                    x-stoplight:
                      id: 01c1ru8vfu63b
      operationId: process
      description: The Process API is called every time interval to process a new print image and update the ML model's state.
      parameters:
        - schema:
            type: string
          in: header
          name: X-API-Key
          description: Your OctoEverywhere API key
      x-stoplight:
        id: ck1qrradzvhim
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Snapshot:
                  type: object
                  x-stoplight:
                    id: hkqu2p39pjsrc
                  description: The new jpg print image.
    parameters:
      - schema:
          type: string
        name: ID
        in: path
        required: true
        description: The context id.
      - schema:
          type: string
        name: ''
        in: path
        required: true
    servers:
      - url: ' https://<your primary process url>.octoeverywhere.com'
        description: ''
components:
  schemas: {}
  securitySchemes: {}
  examples: {}
