openapi: 3.0.0
x-stoplight:
  id: akb7f5psdzhz7
info:
  title: AI Failure Detection APIs
  version: '1.0'
  description: 'API definitions. For a detailed explanation, [see the API overview.](https://octoeverywhere.stoplight.io/docs/octoeverywhere-api-docs/3xadck728cc0t-ai-failure-detection-ap-is)'
servers: []
paths:
  /api/gadget/v1/createcontext:
    parameters: []
    servers:
      - url: 'https://gadget-pv1-oeapi.octoeverywhere.com'
        description: ''
    post:
      summary: Create Context
      tags: []
      responses:
        2XX:
          description: A context was successfully created.
          content:
            application/json:
              schema:
                type: object
                required:
                  - ContextId
                  - ProcessRequestUrl
                  - FallbackProcessRequestUrl
                properties:
                  ContextId:
                    type: string
                    x-stoplight:
                      id: sygaiedhz7i6m
                    description: '        The ID of the new context.'
                    example: uYZkEP0g22nPZwtCj6ASWef9Lpmh81Ahs1mnAdw4Z7PlDFbOK6
                  ProcessRequestUrl:
                    type: string
                    x-stoplight:
                      id: oyrkf6qw3d08g
                    description: '        This is the main URL that should be used for all Process API requests for the lifetime of this context.'
                    example: 'https://gadget-reional-subdomain.octoeverywhere.com/api/gadget/v1/process/uYZkEP0g22nPZwtCj6ASWef9Lpmh81Ahs1mnAdw4Z7PlDFbOK6'
                  FallbackProcessRequestUrl:
                    type: string
                    x-stoplight:
                      id: seqynqf1gba3v
                    description: "    This is the fallback URL that can be used if the `ProcessRequestUrl` fails for any reason. \r\n    Once the application swtiches to the `FallbackProcessRequestUrl` it should continue to use it for the lifetime of the context."
                    example: 'https://gadget-pv1-oeapi.octoeverywhere.com/api/gadget/v1/process/uYZkEP0g22nPZwtCj6ASWef9Lpmh81Ahs1mnAdw4Z7PlDFbOK6'
      operationId: create-context
      x-stoplight:
        id: kgomtjwkt3dj9
      description: "The Create Context API creates a new context for AI failure detection session. The lifetime of a context is a single print, each new print should create a new context.\r\n\r\nThis API should always be called with the primary hostname `gadget-pv1-oeapi.octoeverywhere.com`. Ex: `https://gadget-pv1-oeapi.octoeverywhere.com/api/gadget/v1/createcontex`\r\n\r\nThe context does not need to be destroyed; it will auto-delete after 14 days.\r\n\r\nThe `WarningConfidenceLevel` and `PauseConfidenceLevel` parameters are optional and will adjust how confident the temporal combination model needs to be before invoking the suggestion. The default value is 3, a lower value will mean the model will be less confident and will  \r\n\r\n"
      parameters:
        - schema:
            type: string
          in: header
          name: X-API-Key
          description: You OctoEverywhere developer API key.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                WarningConfidenceLevel:
                  type: integer
                  x-stoplight:
                    id: mfrfza945tj5d
                  minimum: 1
                  maximum: 5
                  description: "```json\r\nOptional Parameter\r\nThis adjusts the temporal combination model's required confidence in a failure to trigger the warning suggestion.\r\nThe value must be between 1-5, where 1 is the least confident (more warnings) and 5 is the most confident (less warnings).\r\nIf not set, the default value of 3 will be used.\r\n```"
                  default: 3
                PauseConfidenceLevel:
                  type: integer
                  x-stoplight:
                    id: wy1w2uz7at298
                  minimum: 1
                  maximum: 5
                  default: 3
                  description: "            Optional Parameter\r\n            This adjusts the temporal combination model's required confidence in a failure to trigger the pause print suggestion.\r\n            The value must be between 1-5, where 1 is the least confident (will pause with less confidence) and 5 is the most confident (will only pause when very confident).\r\n            If not set, the default value of 3 will be used."
  '/api/gadget/v1/process/{ID}':
    get:
      summary: Process API
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  NextProcessIntervalSec:
                    type: integer
                    x-stoplight:
                      id: pjl40jjr6xp76
                    default: 40
                    description: The minimum interval between the response and the next Process API call is in seconds.
                  Score:
                    type: integer
                    x-stoplight:
                      id: yqo01rkjkuc49
                    minimum: 0
                    maximum: 100
                    description: 'The current temporal combination model''s probability of failure. 0 is a perfect print, 100 is very likely a failure.'
                  WarningSuggested:
                    type: boolean
                    x-stoplight:
                      id: ibt3s7is2i87o
                  PauseSuggested:
                    type: boolean
                    x-stoplight:
                      id: 01c1ru8vfu63b
      operationId: process
      description: The Process API is called every time interval to process a new print image and update the ML model's state.
      parameters:
        - schema:
            type: string
          in: header
          name: X-API-Key
          description: Your OctoEverywhere API key
      x-stoplight:
        id: ck1qrradzvhim
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                Snapshot:
                  type: object
                  x-stoplight:
                    id: hkqu2p39pjsrc
                  description: The new jpg print image.
    parameters:
      - schema:
          type: string
        name: ID
        in: path
        required: true
        description: The context id.
      - schema:
          type: string
        name: ''
        in: path
        required: true
    servers:
      - url: ' https://<your primary process url>.octoeverywhere.com'
        description: ''
components:
  schemas: {}
  securitySchemes: {}
  examples: {}
